# Generated by Django 2.2.13 on 2020-06-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('phone', 'Mobiles'), ('tv', 'SmartTV'), ('computer', 'Laptop'), ('earphone', 'Handsfree')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10)),
                ('short_description', models.CharField(max_length=50)),
                ('long_description', models.CharField(max_length=100)),
            ],
        ),
    ]
